# Primer Desafío Fundamentos Data Science

Integrantes: Javier Pilasi, Daniel Flores, Francisco Fernandez, Rocio Ehijo, Máximo Oliva

In [4]:
print("Hola Mundo, esta es mi primera incursión en Python")

Hola Mundo, esta es mi primera incursión en Python

In [ ]:
nombre="Máximo"
edad=28
pasatiempos=["bicicleta", "caminar", "tennis" ]
mascota="si"

In [16]:
print(nombre)
print(edad)
print(pasatiempos)
print(mascota)
print(pasatiempos[1])
print(type(nombre))
print(type(edad))
print(type(pasatiempos))
print(type(mascota))
print(" Mi nombre es {}, tengo {} años, me gusta hacer en mis tiempos libres {} y respecto a mi mascota la respuesta es {}". format (nombre, edad, pasatiempos, mascota))

Máximo
28
['bicicleta', 'caminar', 'tennis']
si
caminar
<class 'str'>
<class 'int'>
<class 'list'>
<class 'str'>
 Mi nombre es Máximo, tengo 28 años, me gusta hacer en mis tiempos libres ['bicicleta', 'caminar', 'tennis'] y respecto a mi mascota la respuesta es si

In [ ]:
print('Estaba la pájara pinta sentada sobre el verde limón')
print("Mi nombre es {} y tengo {} años". format(name, edad))
import pandas as pd
import numpy as np
"Ornitorrinco"+ "45"

# El error del primer enunciado era un error en las comillas finales, la cual no estaba presente
# El error del segundo enunciao era un error en format, no estaba presente
# El error era de escritura, estaba mal escrito pandas
# El eror era de escritura, estaba mal escrito numpy

In [19]:
import pandas as pd 
import numpy as np 

df_flights=pd.read_csv('flights.csv')
print(df_flights.head(5))
print(df_flights[-5:])

print(df_flights['year'].describe())
print(df_flights['year'].value_counts())
print(df_flights['month'].value_counts())

df_primeras15=df_flights[:15]
df_ultimas15=df_flights[-15:]
print(df_primeras15)
print(df_ultimas15)

mediatotal=np.mean(df_flights['passengers'])
medianatotal=(np.median(df_flights['passengers']))
desviacióntotal=(np.std(df_flights['passengers']))
sumatotal=df_flights['passengers'].sum()

media15=np.mean(df_primeras15['passengers'])
mediana15=(np.median(df_primeras15['passengers']))
desviación15=(np.std(df_primeras15['passengers']))
suma15=df_primeras15['passengers'].sum()

media15final=np.mean(df_ultimas15['passengers'])
mediana15final=(np.median(df_ultimas15['passengers']))
desviación15final=(np.std(df_ultimas15['passengers']))
suma15final=df_ultimas15['passengers'].sum()
cv_total=desviacióntotal/mediatotal
cv_primeras=desviación15/media15
cv_final=desviación15final/mediana15final


print("La media total la muestra es de {} pasajeros". format(mediatotal))
print("La mediana total la muestra es de {} pasajeros". format(medianatotal))
print("La desviación estándar de la muestra es de {} pasajeros". format(desviacióntotal))
print("La cantiadad total de pasajeros de la muestra es de {} \n". format(sumatotal))

print("La media de las primeras 15 observaciones de la muestra es de {} pasajeros". format(media15))
print("La mediana de las 15 primeras observaciones de la la muestra es de {} pasajeros". format(mediana15))
print("La desviación estándar de las primeras 15 obsevaciones es de {} pasajeros". format(desviación15))
print("La cantiadad total de pasajeros de las primeras 15 observaciones de la muestra son {} \n". format(suma15))

print("La media de las últimas 15 observaciones de la muestra es de {} pasajeros". format(media15final))
print("La mediana de las 15 últimas observaciones de la la muestra es de {} pasajeros". format(mediana15final))
print("La desviación estándar de las últimas 15 obsevaciones es de {} pasajeros". format(desviación15final))
print("La cantiadad total de pasajeros de las últimas 15 observaciones de la muestra son {} \n". format(suma15final))

print("El coeficiente de Variabilidad de la muestra total es de {}". format(cv_total))
print("El coeficiente de Variabilidad de las primeras 15 observaciones de la muestra es de {}". format(cv_primeras))
print("El coeficiente de Variabilidad de las últimas 15 observaciones de la muestra es de {}". format(cv_final))

# Las últimas 15 observaciones de la muestra presentan una media de 459,2 pasajeros mensuales cifra significativamente mayor 
# a la media de la muestra total que presenta 280,29 pasajeros mensuales  y a la media de  las primeras 15 observaciones,
# las que presentan la menor media con solo 126,8 pasajeros. Por otro lado, las primeras 15 observaciones presentan un menor 
# nivel de dispersión, con un coeficiente de variabilidad de 10% respecto de su media, en contraste con la variabilidad de la
#muestra total que presenta un coeficiente del 42,65% sobre su media.

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121
     year      month  passengers
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432
count     144.000000
mean     1954.500000
std         3.464102
min      1949.000000
25%      1951.750000
50%      1954.500000
75%      1957.250000
max      1960.000000
Name: year, dtype: float64
1960    12
1959    12
1958    12
1957    12
1956    12
1955    12
1954    12
1953    12
1952    12
1951    12
1950    12
1949    12
Name: year, dtype: int64
October      12
May          12
February     12
November     12
April        12
December     12
June         12
September    12
March        12
August       12
January      12
July         12
Name: month, dtype: int64
    year      month  passengers
0   1949    January         112
1   1949   February         118
2   1949      March         132
3   1949      April         129
4   1949        May         121
5   1949       June         135
6   1949       July         148
7   1949     August         148
8   1949  September         136
9   1949    October         119
10  1949   November         104
11  1949   December         118
12  1950    January         115
13  1950   February         126
14  1950      March         141
     year      month  passengers
129  1959    October         407
130  1959   November         362
131  1959   December         405
132  1960    January         417
133  1960   February         391
134  1960      March         419
135  1960      April         461
136  1960        May         472
137  1960       June         535
138  1960       July         622
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432
La media total la muestra es de 280.2986111111111 pasajeros
La mediana total la muestra es de 265.5 pasajeros
La desviación estándar de la muestra es de 119.54904153277148 pasajeros
La cantiadad total de pasajeros de la muestra es de 40363

La media de las primeras 15 observaciones de la muestra es de 126.8 pasajeros
La mediana de las 15 primeras observaciones de la la muestra es de 126.0 pasajeros
La desviación estándar de las primeras 15 obsevaciones es de 12.681745410891462 pasajeros
La cantiadad total de pasajeros de las primeras 15 observaciones de la muestra son 1902

La media de las últimas 15 observaciones de la muestra es de 459.2 pasajeros
La mediana de las 15 últimas observaciones de la la muestra es de 432.0 pasajeros
La desviación estándar de las últimas 15 obsevaciones es de 75.29426715671431 pasajeros
La cantiadad total de pasajeros de las últimas 15 observaciones de la muestra son 6888

El coeficiente de Variabilidad de la muestra total es de 0.42650600749991563
El coeficiente de Variabilidad de las primeras 15 observaciones de la muestra es de 0.10001376507012194
El coeficiente de Variabilidad de las últimas 15 observaciones de la muestra es de 0.17429228508498684